name: Validate

on:
  pull_request:
    branches: [ main ]

  workflow_dispatch:

jobs:
  close_prs:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Install GitHub CLI
        run: |
          sudo apt-key adv --keyserver keyserver.ubuntu.com --recv-key C99B11DEB97541F0
          sudo apt-add-repository https://cli.github.com/packages
          sudo apt update
          sudo apt install gh

      - name: Close PRs (with no description)
        run: |
          gh auth login --with-token <<< "${{ secrets.GITHUB_TOKEN }}"
          for pr in $gh pr list --json number,title,body -q '.[] | select.(.body == "") | .number'); do
            gh pr close $pr
          done


  build:
    runs-on: ubuntu-latest

    defaults:
      run:
        working-directory: ./app/

    strategy:
      matrix:
        python-version: [3.11]

    steps:
      - uses: actions/checkout@v3
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r ../requirements.txt

      - name: Run tests
        run: |
          python ./test_main.py